services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    env_file:
      - .env

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"